name: battery_plus
description: Flutter plugin for accessing information about the battery state(full, charging, discharging).
version: 2.1.4
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.battery
        pluginClass: BatteryPlusPlugin
      ios:
        pluginClass: FLTBatteryPlusPlugin
      linux:
        default_package: battery_plus_linux
      macos:
        default_package: battery_plus_macos
      web:
        default_package: battery_plus_web
      windows:
        default_package: battery_plus_windows

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  battery_plus_platform_interface:
    path: ../battery_plus_platform_interface
  battery_plus_linux:
    path: ../battery_plus_linux
  battery_plus_macos:
    path: ../battery_plus_macos
  battery_plus_web:
    path: ../battery_plus_web
  battery_plus_windows:
    path: ../battery_plus_windows

dev_dependencies:
  flutter_test:
    sdk: flutter

  async: ^2.8.2
  plugin_platform_interface: ^2.1.2
  test: ^1.16.4
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"