name: battery_plus_windows
description: Windows implementation of the battery_plus plugin
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  battery_plus_platform_interface:
    path: ../battery_plus_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: BatteryPlusWindowsPlugin
